site_name: Regularizing the Forward Pass  
site_url: https://pharringtonp19.github.io/rfp/
site_description: pure functions <=> pure simplicity
site_author: Patrick Power


nav:
  - Philosphy: index.md
  - Generalizing Across Clusters: "Generalizing Across Clusters.md"
  - Deep Controls: "deep_controls.md"
  - Implementation (JAX): 
    - Neural Network Models: Implementation/networks.md
    - Training: Implementation/train.md
    - Losses: Implementation/losses.md
    - Toy Data Sets: Implementation/data.md
    - Utils: Implementation/utils.md

theme:
  name: "material"

plugins:
  - mkdocstrings

markdown_extensions:
    - attr_list
    - md_in_html
    - pymdownx.superfences
    - admonition
    - pymdownx.details