site_name: Regularizing the Forward Pass  
site_url: https://pharringtonp19.github.io/rfp/
site_description: Enabled by Jax
site_author: Patrick Power


nav:
  - Flavor of Causal Inference: index.md
  - Generalizing Across Clusters: "papers/Generalizing_Across_Clusters.pdf"
  - Unintended Consequences of Right to Counsel: "papers/Unintended_Consequences_of_a_Right_to_Counsel.pdf"
  - Score Guided Attention: "papers/Score_Guided_Attention.pdf"
    #- Overview: "generalizing_across_clusters/overview.md"
    #- The Problem: "generalizing_across_clusters/the_problem.md"
  #- Deep Controls: "deep_controls.md"
  #- Research Question: "rtc.md"
  - Implementation (JAX): 
    - Neural Network Models: Implementation/networks.md
    - Training: "Implementation/train.md"
    - Losses: Implementation/losses.md
    - Toy Data Sets: Implementation/data.md
    - Utils: Implementation/utils.md
    - Feature Map: 'Implementation/featuremap.md'
    - Kernels: 'Implementation/kernels.md'

theme:
  name: material
  palette:
    scheme: default
    primary: blue
  icon:
    admonition:
      code: fontawesome/solid/code
      note: octicons/tag-16
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
    - navigation.top
    #- navigation.tabs.sticky

plugins:
  - mkdocstrings

markdown_extensions:
    - attr_list
    - md_in_html
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - admonition
    - pymdownx.details
    - pymdownx.arithmatex:  # Render LaTeX via MathJax
        generic: true
    - footnotes
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript: 
    # The below three make MathJax work, see https://squidfunk.github.io/mkdocs-material/reference/mathjax/
    - _static/mathjax.js
    - https://polyfill.io/v3/polyfill.min.js?features=es6
    - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js